In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../../data/raw/dataset-case-iqvia.csv')

In [4]:
df.head()

,week_dt,dsupp_id,product_id,region_nm,units_qty,product_attr_1,product_attr_2,product_attr_3
0,2024-03-31,6,233,Norte,6.0,B,C,B24
1,2024-03-01,6,233,Norte,1.0,B,C,B24
2,2024-08-01,6,233,Norte,1.0,B,C,B24
3,2024-09-29,6,233,Norte,1.0,B,C,B24
4,2024-05-01,6,233,Norte,3.0,B,C,B24

In [5]:
df.tail()

,week_dt,dsupp_id,product_id,region_nm,units_qty,product_attr_1,product_attr_2,product_attr_3
147289,2024-07-07,6,36,Norte,51.0,C,B,B04
147290,2024-07-07,6,36,Nordeste,135.0,C,B,B04
147291,2024-08-25,6,36,Nordeste,644.0,C,B,B04
147292,2024-08-25,6,36,Norte,243.0,C,B,B04
147293,2024-08-25,6,36,Centro-Oeste,21.0,C,B,B04

In [6]:
df.columns = ['week_date','supplier_id','product_id','region','units_sold','product_attribute_1','product_attribute_2','product_attribute_3']

In [7]:
df.head()

,week_date,supplier_id,product_id,region,units_sold,product_attribute_1,product_attribute_2,product_attribute_3
0,2024-03-31,6,233,Norte,6.0,B,C,B24
1,2024-03-01,6,233,Norte,1.0,B,C,B24
2,2024-08-01,6,233,Norte,1.0,B,C,B24
3,2024-09-29,6,233,Norte,1.0,B,C,B24
4,2024-05-01,6,233,Norte,3.0,B,C,B24

In [8]:
df.dtypes

week_date               object
supplier_id              int64
product_id               int64
region                  object
units_sold             float64
product_attribute_1     object
product_attribute_2     object
product_attribute_3     object
dtype: object

In [12]:
df['week_date'] = pd.to_datetime(df['week_date'], format='%Y-%m-%d')
df['supplier_id'] = df['supplier_id'].astype('object')
df['product_id'] = df['product_id'].astype('object')
df['units_sold'] = df['units_sold'].astype('int')

In [13]:
df.dtypes

week_date              datetime64[ns]
supplier_id                    object
product_id                     object
region                         object
units_sold                      int32
product_attribute_1            object
product_attribute_2            object
product_attribute_3            object
dtype: object

In [14]:
df.to_parquet('../../data/bronze/iqvia-sales_data.parquet', index=False)