In [161]:
import pandas as pd
from matplotlib import pyplot as plt

In [162]:
df = pd.read_parquet('../../data/bronze/iqvia-sales_data.parquet')

In [163]:
df_dim_time = pd.DataFrame({'date': pd.date_range(
    start=df['week_date'].min(),
    end=df['week_date'].max(),
    freq='D'
)})

df_dim_time['year'] = df_dim_time['date'].dt.year
df_dim_time['semester'] = df_dim_time['date'].dt.month.apply(lambda x: 1 if x <= 6 else 2)
df_dim_time['semester_date'] = pd.to_datetime(df_dim_time['date'].dt.to_period('6M').apply(lambda r: r.start_time))
df_dim_time['semester_name'] = df_dim_time['semester'].apply(lambda x: 'H1' if x == 1 else 'H2')
df_dim_time['quarter'] = df_dim_time['date'].dt.quarter
df_dim_time['quarter_date'] = pd.to_datetime(df_dim_time['date'].dt.to_period('Q').apply(lambda r: r.start_time))
df_dim_time['quarter_name'] = df_dim_time['quarter'].apply(lambda x: f'Q{x}')
df_dim_time['month'] = df_dim_time['date'].dt.month
df_dim_time['month_name'] = df_dim_time['date'].dt.month_name()
df_dim_time['month_date'] = pd.to_datetime(df_dim_time['date'].dt.to_period('M').apply(lambda r: r.start_time))
df_dim_time['day'] = df_dim_time['date'].dt.day
df_dim_time['week'] = df_dim_time['date'].dt.isocalendar().week
df_dim_time['week_date'] = pd.to_datetime(df_dim_time['date'].dt.to_period('W').apply(lambda r: r.start_time))
df_dim_time['day_of_week'] = df_dim_time['date'].dt.dayofweek
df_dim_time['day_of_week_name'] = df_dim_time['date'].dt.day_name()

df_dim_time.reset_index(inplace=True)
df_dim_time.rename(columns={'index': 'date_id'}, inplace=True)
df_dim_time['date_id'] += 1
df_dim_time.head(10)

,date_id,date,year,semester,semester_date,semester_name,quarter,quarter_date,quarter_name,month,month_name,month_date,day,week,week_date,day_of_week,day_of_week_name
0,1,2022-11-01,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,1,44,2022-10-31,1,Tuesday
1,2,2022-11-02,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,2,44,2022-10-31,2,Wednesday
2,3,2022-11-03,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,3,44,2022-10-31,3,Thursday
3,4,2022-11-04,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,4,44,2022-10-31,4,Friday
4,5,2022-11-05,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,5,44,2022-10-31,5,Saturday
5,6,2022-11-06,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,6,44,2022-10-31,6,Sunday
6,7,2022-11-07,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,7,45,2022-11-07,0,Monday
7,8,2022-11-08,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,8,45,2022-11-07,1,Tuesday
8,9,2022-11-09,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,9,45,2022-11-07,2,Wednesday
9,10,2022-11-10,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,10,45,2022-11-07,3,Thursday

In [164]:
df_dim_time.head(10)

,date_id,date,year,semester,semester_date,semester_name,quarter,quarter_date,quarter_name,month,month_name,month_date,day,week,week_date,day_of_week,day_of_week_name
0,1,2022-11-01,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,1,44,2022-10-31,1,Tuesday
1,2,2022-11-02,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,2,44,2022-10-31,2,Wednesday
2,3,2022-11-03,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,3,44,2022-10-31,3,Thursday
3,4,2022-11-04,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,4,44,2022-10-31,4,Friday
4,5,2022-11-05,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,5,44,2022-10-31,5,Saturday
5,6,2022-11-06,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,6,44,2022-10-31,6,Sunday
6,7,2022-11-07,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,7,45,2022-11-07,0,Monday
7,8,2022-11-08,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,8,45,2022-11-07,1,Tuesday
8,9,2022-11-09,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,9,45,2022-11-07,2,Wednesday
9,10,2022-11-10,2022,2,2022-11-01,H2,4,2022-10-01,Q4,11,November,2022-11-01,10,45,2022-11-07,3,Thursday

In [165]:
df_dim_time.to_parquet('../../data/silver/dim_calendar.parquet', index=False)

In [166]:
df_dim_supplier = pd.DataFrame({'supplier_id': df['supplier_id'].sort_values().unique()})
df_dim_supplier['supplier_name'] = df_dim_supplier['supplier_id'].apply(lambda x: f'Supplier {x}')
df_dim_supplier.head(10)

   supplier_id supplier_name
0            1    Supplier 1
1            2    Supplier 2
2            3    Supplier 3
3            4    Supplier 4
4            5    Supplier 5
5            6    Supplier 6
6            7    Supplier 7
7            8    Supplier 8
8            9    Supplier 9
9           10   Supplier 10

In [167]:
df_dim_supplier.to_parquet('../../data/silver/dim_supplier.parquet', index=False)

In [168]:
df_dim_region = pd.DataFrame(df['region'].sort_values().unique()).reset_index()
df_dim_region.columns = ['region_id','region_name']
df_dim_region['region_id'] += 1
df_dim_region.head(10)

   region_id   region_name
0          1  Centro-Oeste
1          2      Nordeste
2          3         Norte
3          4       Sudeste
4          5           Sul

In [169]:
df_dim_region.to_parquet('../../data/silver/dim_region.parquet', index=False)

In [170]:
len(df['product_id'].sort_values().unique())

390

In [171]:
df_dim_product = df[['product_id','product_attribute_1','product_attribute_2','product_attribute_3']].drop_duplicates().sort_values('product_id').reset_index(drop=True)
df_dim_product['product_name'] = df_dim_product['product_id'].apply(lambda x: f'Product {x}')
df_dim_product.head(10)

,product_id,product_attribute_1,product_attribute_2,product_attribute_3,product_name
0,1,B,C,B24,Product 1
1,2,B,C,B16,Product 2
2,3,A,A,A08,Product 3
3,4,B,C,B24,Product 4
4,5,B,C,B32,Product 5
5,6,C,C,B21,Product 6
6,7,B,C,B21,Product 7
7,8,B,C,B28,Product 8
8,9,B,C,B24,Product 9
9,10,B,C,B13,Product 10

In [172]:
df_dim_product.head()

,product_id,product_attribute_1,product_attribute_2,product_attribute_3,product_name
0,1,B,C,B24,Product 1
1,2,B,C,B16,Product 2
2,3,A,A,A08,Product 3
3,4,B,C,B24,Product 4
4,5,B,C,B32,Product 5

In [173]:
df_dim_product.to_parquet('../../data/silver/dim_product.parquet', index=False)

In [174]:
df_fact_sales

        sales_id  date_id  supplier_id  region_id  product_id  units_sold
0              1    511.0            6          3         233           6
1              2    483.0            6          3         233           1
2              3    637.0            6          3         233           1
3              4    693.0            6          3         233           1
4              5    546.0            6          3         233           3
...          ...      ...          ...        ...         ...         ...
147289    147290    609.0            6          3          36          51
147290    147291    609.0            6          2          36         135
147291    147292    658.0            6          2          36         644
147292    147293    658.0            6          3          36         243
147293    147294    658.0            6          1          36          21

[147294 rows x 6 columns]

In [175]:
df_fact_sales = df[['week_date','supplier_id','product_id','region','units_sold']]
df_fact_sales.tail()

        week_date  supplier_id  product_id        region  units_sold
147289 2024-07-07            6          36         Norte          51
147290 2024-07-07            6          36      Nordeste         135
147291 2024-08-25            6          36      Nordeste         644
147292 2024-08-25            6          36         Norte         243
147293 2024-08-25            6          36  Centro-Oeste          21

In [ ]:
df_fact_sales = df[['week_date','supplier_id','product_id','region','units_sold']]
df['week_date'] = df['week_date'].dt.to_period('W').dt.to_timestamp() #ajustar para a data da semana correta (ISO)
df_fact_sales = (df_fact_sales
.merge(df_dim_time[['date','date_id']], left_on='week_date', right_on='date', how='left').drop(columns=['date'])
.merge(df_dim_region[['region_id','region_name']], left_on='region', right_on='region_name', how='left').drop(columns=['region','region_name'])
)
df_fact_sales.head()

   week_date  supplier_id  product_id  units_sold  date_id  region_id
0 2024-03-31            6         233           6      517          3
1 2024-03-01            6         233           1      487          3
2 2024-08-01            6         233           1      640          3
3 2024-09-29            6         233           1      699          3
4 2024-05-01            6         233           3      548          3

In [177]:
df_fact_sales[df_fact_sales['week_date'] == '2022-10-31']

Empty DataFrame
Columns: [week_date, supplier_id, product_id, units_sold, date_id, region_id]
Index: []

In [178]:
df_fact_sales = df_fact_sales[['date_id','supplier_id','region_id','product_id','units_sold']]
df_fact_sales.reset_index(inplace=True)
df_fact_sales.rename(columns={'index': 'sales_id'}, inplace=True)
df_fact_sales['sales_id'] += 1
df_fact_sales.to_parquet('../../data/silver/fact_sales.parquet', index=False)

In [179]:
df_fact_sales

        sales_id  date_id  supplier_id  region_id  product_id  units_sold
0              1      517            6          3         233           6
1              2      487            6          3         233           1
2              3      640            6          3         233           1
3              4      699            6          3         233           1
4              5      548            6          3         233           3
...          ...      ...          ...        ...         ...         ...
147289    147290      615            6          3          36          51
147290    147291      615            6          2          36         135
147291    147292      664            6          2          36         644
147292    147293      664            6          3          36         243
147293    147294      664            6          1          36          21

[147294 rows x 6 columns]